// Site search.
//
// The site is static, so this runs entirely in the browser against
// /search.json (generated by src/pages/search.json.js). The index is fetched
// once, the first time the panel is opened — it is never on the critical path
// for a page load, and a visitor who never searches never downloads it.
//
// Kept out of main.js on purpose: this is self-contained, and main.js is one
// long DOMContentLoaded callback that unrelated features have to share.

document.addEventListener('DOMContentLoaded', function () {
    var panel = document.getElementById('site-search');
    var toggle = document.getElementById('search-toggle');
    var input = document.getElementById('site-search-input');
    var list = document.getElementById('site-search-results');
    var empty = document.querySelector('.site-search-empty');
    var closeBtn = document.querySelector('.site-search-close');
    if (!panel || !toggle || !input || !list) return;

    var docs = null;          // the index, once fetched
    var loading = false;
    var results = [];
    var active = -1;
    var lastQuery = '';

    // ---- index ------------------------------------------------------------

    function loadIndex() {
        if (docs || loading) return Promise.resolve();
        loading = true;
        return fetch('/search.json')
            .then(function (r) { return r.json(); })
            .then(function (data) {
                // Pre-lowercase once, so scoring never lowercases in a loop.
                docs = data.map(function (d) {
                    d._t = d.t.toLowerCase();
                    d._k = (d.k || '').toLowerCase();
                    d._d = (d.d || '').toLowerCase();
                    d._b = (d.b || '').toLowerCase();
                    return d;
                });
                loading = false;
                if (input.value.trim()) run(input.value);
            })
            .catch(function () {
                loading = false;
                list.innerHTML = '';
                empty.textContent = 'Search is unavailable right now. Please try again.';
                empty.hidden = false;
            });
    }

    // ---- scoring ----------------------------------------------------------

    // Substring matching, so "roof" finds "roofing" and "cement" finds
    // "micro-cement" without needing a stemmer. Every term must appear
    // somewhere in a document for it to match at all.
    function score(doc, terms) {
        var total = 0;
        for (var i = 0; i < terms.length; i++) {
            var term = terms[i];
            var inTitle = doc._t.indexOf(term);
            var inKind = doc._k.indexOf(term) !== -1;
            var inDesc = doc._d.indexOf(term) !== -1;
            var inBody = doc._b.indexOf(term) !== -1;
            if (inTitle === -1 && !inKind && !inDesc && !inBody) return 0;
            if (inTitle === 0) total += 60;
            else if (inTitle > 0) total += 40;
            if (inKind) total += 15;
            if (inDesc) total += 12;
            if (inBody) total += 4;
        }
        // Reward the whole phrase appearing intact.
        var phrase = terms.join(' ');
        if (terms.length > 1) {
            if (doc._t.indexOf(phrase) !== -1) total += 40;
            else if (doc._d.indexOf(phrase) !== -1 || doc._b.indexOf(phrase) !== -1) total += 12;
        }
        return total;
    }

    function search(query) {
        var terms = query.toLowerCase().split(/\s+/).filter(function (t) { return t.length > 1; });
        if (!terms.length) return [];
        var hits = [];
        for (var i = 0; i < docs.length; i++) {
            // The per-type weight from the index keeps thin listing pages from
            // outranking the product and article pages they point at.
            var s = score(docs[i], terms) * (docs[i].w || 1);
            if (s > 0) hits.push({ doc: docs[i], score: s, terms: terms });
        }
        hits.sort(function (a, b) { return b.score - a.score; });
        return hits.slice(0, 8);
    }

    // ---- rendering --------------------------------------------------------

    function escapeHtml(text) {
        return text.replace(/[&<>"]/g, function (c) {
            return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c];
        });
    }

    function highlight(text, terms) {
        var safe = escapeHtml(text);
        for (var i = 0; i < terms.length; i++) {
            var pattern = terms[i].replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
            safe = safe.replace(new RegExp('(' + pattern + ')', 'gi'), '<mark>$1</mark>');
        }
        return safe;
    }

    // A window of body text around the first matching term, so the result
    // shows why it matched rather than just repeating the description.
    function snippet(doc, terms) {
        var at = -1;
        for (var i = 0; i < terms.length && at < 0; i++) at = doc._b.indexOf(terms[i]);
        if (at < 0) return doc.d || '';
        var start = Math.max(0, at - 60);
        var end = Math.min(doc.b.length, at + 110);
        return (start > 0 ? '…' : '') + doc.b.slice(start, end).trim() + (end < doc.b.length ? '…' : '');
    }

    function render(hits, query) {
        results = hits;
        active = -1;
        if (!query.trim()) {
            list.innerHTML = '';
            empty.hidden = true;
            input.setAttribute('aria-expanded', 'false');
            return;
        }
        if (!hits.length) {
            list.innerHTML = '';
            empty.textContent = 'No matches for “' + query.trim() + '”. Try a different word.';
            empty.hidden = false;
            input.setAttribute('aria-expanded', 'false');
            return;
        }
        empty.hidden = true;
        input.setAttribute('aria-expanded', 'true');
        list.innerHTML = hits.map(function (hit, i) {
            return '<li role="option" id="search-hit-' + i + '" aria-selected="false">' +
                '<a href="' + hit.doc.u + '">' +
                '<span class="search-hit-kind">' + escapeHtml(hit.doc.k || '') + '</span>' +
                '<span class="search-hit-title">' + highlight(hit.doc.t, hit.terms) + '</span>' +
                '<span class="search-hit-snippet">' + highlight(snippet(hit.doc, hit.terms), hit.terms) + '</span>' +
                '</a></li>';
        }).join('');
    }

    function run(query) {
        if (!docs) { loadIndex(); return; }
        lastQuery = query;
        render(search(query), query);
    }

    // ---- selection --------------------------------------------------------

    function setActive(next) {
        var items = list.children;
        if (!items.length) return;
        if (active >= 0 && items[active]) items[active].setAttribute('aria-selected', 'false');
        active = (next + items.length) % items.length;
        items[active].setAttribute('aria-selected', 'true');
        input.setAttribute('aria-activedescendant', items[active].id);
        items[active].scrollIntoView({ block: 'nearest' });
    }

    // ---- open / close -----------------------------------------------------

    function open() {
        panel.hidden = false;
        toggle.setAttribute('aria-expanded', 'true');
        // Flush styles so the fade has a state to move from.
        void panel.offsetWidth;
        panel.classList.add('open');
        input.focus();
        loadIndex();
    }

    function close() {
        panel.classList.remove('open');
        toggle.setAttribute('aria-expanded', 'false');
        input.blur();
        window.setTimeout(function () {
            if (!panel.classList.contains('open')) panel.hidden = true;
        }, 200);
    }

    var isOpen = function () { return panel.classList.contains('open'); };

    toggle.addEventListener('click', function () { isOpen() ? close() : open(); });
    if (closeBtn) closeBtn.addEventListener('click', close);

    // Clicking the backdrop closes; clicking inside the panel does not.
    panel.addEventListener('click', function (e) { if (e.target === panel) close(); });

    var timer = null;
    input.addEventListener('input', function () {
        var value = input.value;
        window.clearTimeout(timer);
        timer = window.setTimeout(function () { run(value); }, 120);
    });

    input.addEventListener('keydown', function (e) {
        if (e.key === 'ArrowDown') { e.preventDefault(); setActive(active + 1); }
        else if (e.key === 'ArrowUp') { e.preventDefault(); setActive(active - 1); }
        else if (e.key === 'Enter') {
            var link = list.children[active < 0 ? 0 : active];
            if (link) { e.preventDefault(); link.querySelector('a').click(); }
        }
    });

    document.addEventListener('keydown', function (e) {
        if (e.key === 'Escape' && isOpen()) { close(); toggle.focus(); return; }
        // "/" opens search, the way it does on most documentation sites -- but
        // not while the visitor is typing into a field.
        if (e.key === '/' && !isOpen()) {
            var tag = (e.target.tagName || '').toLowerCase();
            if (tag === 'input' || tag === 'textarea' || e.target.isContentEditable) return;
            e.preventDefault();
            open();
        }
    });
});
